version: '3.4'

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443


  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: unless-stopped

  guacamole:
    container_name: guacamole
    image: guacamole/guacamole
    restart: unless-stopped
    depends_on:
      - guacd
    ports:
      - "8080:8080"
    enviroment:
      - GUACD_HOSTNAME: guacd
      - POSTGRES_HOSTNAME: postgres
      - POSTGRES_DATABASE: guacamole
      - POSTGRES_USER: guacamole
      - POSTGRES_PASSWORD: password
      - VIRTUAL_PORT: 8080
    # - VIRUTAL_HOST: 127.0.0.1

  postgres:
    image: postgres:latest
    restart: unless-stopped
    enviroment:
      - POSTGRES_USER: gacamole
      - POSTGRES_PASSWORD: password
