# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu

pipelines:
  default:
    - step:
        name: 'Validation of Heat templates'
        script:
          - export DEBIAN_FRONTEND=noninteractive
          - apt update -yq
          - apt install python3-openstackclient -yq
          - apt install python3-openstacksdk -yq
          - chown 0600 project/gruppe4RC.sh
          - source project/gruppe4RC.sh
          - openstack stack create --dry-run -t project/iac_top.yaml -e project/iac_top_env.yaml project

#    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
#    - step:
#        name: 'Deployment to Staging'
#        deployment: staging
#        script:
#          - echo "Your deployment to staging script goes here..."
#    - step:
#        name: 'Deployment to Production'
#        deployment: production
#        trigger: 'manual'
#        script:
#          - echo "Your deployment to production script goes here..."
#
